### ISSUE TITLE
reWASD config

### ISSUE THREAD

**Issue by Jok3rTr1ckster** [vStar925/RDR1-Keyboard-Mouse#3] opened 2023-07-03 19:57 UTC
I followed the steps and got into the game. I was able to use the keyboard to start the game and I got past the opening cutscene. However, when John steps off the train, I couldn't use my mouse to look around. After investigating myself, I discovered that on my mouse profile it said that the mapping wouldn't work because the feature was locked. Any idea how to fix this?
![Screenshot (80)](https://github.com/vStar925/RDR1-Keyboard-Mouse/assets/138526495/c1e9f914-b467-45ad-8758-1090e43cc636)

**Comment by vStar925** [comment] 2023-07-03 20:05
Hmm, that's odd. The feature being locked means it's a paid feature but up top it says you still have a trial. I'm pretty sure all features are supposed to be available during the trial. There's 3 things I can think of to try.

1.) Contact reWASD

2.) Right-click the arrows on the mouse and clear the config. Then assign it to the right stick manually. If it's not letting you use some features, when you clear it you probably won't have the extra tweaks so it may not feel as intended. But still worth a shot.

3.) Buy the software.

**Comment by Jok3rTr1ckster** [comment] 2023-07-03 20:27
It appears that some of the button mappings are locked behind a paywall, most notably the right stick. Tbh, the reWASD software is a little confusing at first. You could buy the software, but it's $25 to gain access to everything. I'm able to use the software with a trial period of 3 days.

**Closed as completed** 2023-07-04 03:26 UTC

**Comment by Bartek16194** [comment] 2023-07-04 15:26
I have this problem too, the program is paid and it's a pity that the creator did not deign to inform about it before wasting our time

**Comment by vStar925** [comment] 2023-07-04 15:28
> I have this problem too, the program is paid and it's a pity that the creator did not deign to inform about it before wasting our time

The software page literally says it's paid with a trial option...

**Comment by vStar925** [comment] 2023-07-04 16:18
reWASD is paid software with a 7 day trial. The advanced features require a separate 3 day trial.

https://twitter.com/Doonishsan/status/1676267406040403968?s=20
